version: '3'
services:
  frontend:
    build:
      context: ./frontend # フロントエンドのDockerfileがあるディレクトリを指定
    ports:
      - "3000:3000" # フロントエンドのポート
    depends_on:
      - backend
  backend:
    build:
      context: ./backend # バックエンドのDockerfileがあるディレクトリを指定
    ports:
      - "5000:5000" # バックエンドのポート
    environment:
      POSTGRES_HOST: db # データベースのホスト名を指定
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
